language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
python:
  - 3.8
install:
  - pip install pipenv
  - pipenv sync -d
  - pipenv install flake8 --dev
script:
  - pipenv run flake8 .